# Generated by Django 2.2.2 on 2019-07-23 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CURDATA',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
                ('ch', models.IntegerField()),
                ('c_avr', models.FloatField()),
                ('c_max', models.FloatField()),
            ],
        ),
    ]
